import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut >
            <SignInButton className="ml-[1000px] mt-[500px] w-[150px] h-[60px] rounded-[40px] bg-blue-500 border border-gray-600"/>
          </SignedOut>
          <SignedIn>{children} </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
